//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VentaPresentacion {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.6.0.0")]
    internal sealed partial class ConfiguracionApp : global::System.Configuration.ApplicationSettingsBase {
        
        private static ConfiguracionApp defaultInstance = ((ConfiguracionApp)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new ConfiguracionApp())));
        
        public static ConfiguracionApp Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double PorcentajeGanancia {
            get {
                return ((double)(this["PorcentajeGanancia"]));
            }
            set {
                this["PorcentajeGanancia"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.12")]
        public double Iva {
            get {
                return ((double)(this["Iva"]));
            }
            set {
                this["Iva"] = value;
            }
        }
    }
}
